export const ITEMS_SINGLES = [
  { num: 1, id: "9edly03xlg", title: "4 Ways Hero Can Stress A Villain" },
  { num: 2, id: "unpxciatnf", title: "Court Positioning & Geometry" },
  { num: 3, id: "077w305zxc", title: "Sword & Shield" },
  { num: 4, id: "vqm9x2khzi", title: "Inside & Outside Groundstrokes" },
  { num: 5, id: "8aqmqb4t0p", title: "The Red Zone" },
  { num: 6, id: "vb22efs9is", title: "The 2-1" },
  { num: 7, id: "34i4kgquc8", title: "Beating The Pusher" },
  { num: 8, id: "drlnlbad2j", title: "Serving vs. Pusher - Serve + 1" },
  { num: 9, id: "ac5ie1ce2n", title: "Returning vs Pusher" },
  {
    num: 10,
    id: "vbqd9ip2yg",
    title: "Rallying vs Pusher - Modified Punisher",
  },
  { num: 11, id: "70q2fziibx", title: "Approaching vs Pusher - The Newt" },
  { num: 12, id: "zed4sca6fb", title: "Pushers Love The Bulldozer" },
  { num: 13, id: "imerauw2iv", title: "Beating The Counter-Puncher" },
  { num: 14, id: "cc9wcc0v51", title: "Serving vs Counter-Puncher" },
  { num: 15, id: "lnbrlrvcyi", title: "Returning vs Counter-Puncher" },
  {
    num: 16,
    id: "w6loausnnd",
    title: "Rallying vs Counter-Puncher - The Swiss Watch",
  },
  {
    num: 17,
    id: "5574t3zu1s",
    title: "Rallying vs Counter-Puncher - Trench Warfare",
  },
  { num: 18, id: "1si0c80weh", title: "Approaching vs Counter-Puncher" },
  { num: 19, id: "d5u2c6cz5q", title: "Counter-Punchers Love The Layup" },
  { num: 20, id: "726oua50oz", title: "Beating The Aggressive Baseliner" },
  { num: 21, id: "4r5i15rieb", title: "Serving vs Aggressive Baseliner" },
  { num: 22, id: "xvvyg9lyxc", title: "Returning vs Aggressive Baseliner" },
  {
    num: 23,
    id: "go53mci5c7",
    title: "Rallying vs Aggressive Baseliner - Trench Warfare",
  },
  {
    num: 24,
    id: "clt8zikjc1",
    title: "Rallying vs Aggressive Baseliner - Home Base",
  },
  {
    num: 25,
    id: "65ydldv89e",
    title: "Approaching vs Aggressive Baseliner - The Newt",
  },
  {
    num: 26,
    id: "kvpgrrfmd4",
    title: "Aggressive Baseliners Love The Bulldozer",
  },
  { num: 27, id: "xu253uanj2", title: "Beating The Serve & Volleyer" },
  { num: 28, id: "yhljlpuxwc", title: "Serving vs Serve & Volleyer" },
  {
    num: 29,
    id: "9b4spgjzjq",
    title: "Returning vs Serve & Volleyer - The Lleyton",
  },
  {
    num: 30,
    id: "wm1kpgxvrz",
    title: "Rallying vs Serve & Volleyer - Trench Warfare",
  },
  {
    num: 31,
    id: "q0r90re1g0",
    title: "Rallying vs Serve & Volleyer - Home Base",
  },
  { num: 32, id: "c7phcyssm6", title: "Approaching vs Serve & Volleyer" },
  { num: 33, id: "lrdw6z4thx", title: "Serve & Volleyers Love The Newt" },
  { num: 34, id: "reepf7ssdd", title: "Beating Dr. Feelgood" },
  { num: 35, id: "kddoqqyejw", title: "Serving vs Dr. Feelgood - Serve + 1" },
  { num: 36, id: "cnsnii2eqa", title: "Returning vs Dr. Feelgood" },
  {
    num: 37,
    id: "ucwmxhsol7",
    title: "Rallying vs Dr. Feelgood - The Punisher",
  },
  {
    num: 38,
    id: "74oq3anfy3",
    title: "Approaching vs Dr. Feelgood - The Bulldozer",
  },
  { num: 39, id: "je08piiuaa", title: "Dr. Feelgood Loves The Newt" },
  { num: 40, id: "ct01b36ksk", title: "Beating The All-Court Player" },
  { num: 41, id: "xeyom7omsq", title: "Serving vs All-Court Player" },
  {
    num: 42,
    id: "4wjhlsutac",
    title: "Returning vs All-Court Player - Return + 1",
  },
  {
    num: 43,
    id: "y138qyekql",
    title: "Rallying vs All-Court Player - Home Base",
  },
  {
    num: 44,
    id: "8afl4uwywn",
    title: "Rallying vs All-Court Player - Trench Warfare",
  },
  {
    num: 45,
    id: "ntnwy6dus8",
    title: "Approaching vs All-Court Player - The Bulldozer",
  },
  { num: 46, id: "40sc3w3mft", title: "All-Court Players Love The Newt" },
  { num: 47, id: "1f1csbkfwy", title: "Beating The SouthPaw" },
  {
    num: 48,
    id: "5ej4g1ozc7",
    title: "Sword & Shield Are Now Reversed For Villain!",
  },
  { num: 49, id: "86u3xrxmnk", title: "Serving vs SouthPaw" },
  { num: 50, id: "04r7bta5fm", title: "Returning vs SouthPaw" },
  {
    num: 51,
    id: "mrb973wds5",
    title: "Rallying vs Southpaw - The Battering Ram",
  },
  {
    num: 52,
    id: "ez5m7aduet",
    title: "Rallying vs SouthPaw - The Mexican Standoff",
  },
  {
    num: 53,
    id: "b31vum6nob",
    title: "Approaching vs SouthPaw - The Bulldozer",
  },
  { num: 54, id: "fyqj1hwtd5", title: "SouthPaws Love The Bulldozer" },
];
